################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../selex-fdk/libs/canopen-clib/CO.c \
../selex-fdk/libs/canopen-clib/CO_CAN_Msg.c \
../selex-fdk/libs/canopen-clib/CO_CRC.c \
../selex-fdk/libs/canopen-clib/CO_EMCY.c \
../selex-fdk/libs/canopen-clib/CO_FLASH.c \
../selex-fdk/libs/canopen-clib/CO_NMT.c \
../selex-fdk/libs/canopen-clib/CO_OD.c \
../selex-fdk/libs/canopen-clib/CO_OD_sign.c \
../selex-fdk/libs/canopen-clib/CO_OD_storage.c \
../selex-fdk/libs/canopen-clib/CO_Object.c \
../selex-fdk/libs/canopen-clib/CO_PDO.c \
../selex-fdk/libs/canopen-clib/CO_RPDO.c \
../selex-fdk/libs/canopen-clib/CO_SDO.c \
../selex-fdk/libs/canopen-clib/CO_SDOclient.c \
../selex-fdk/libs/canopen-clib/CO_SDOserver.c \
../selex-fdk/libs/canopen-clib/CO_SYNC.c \
../selex-fdk/libs/canopen-clib/CO_TPDO.c 

C_DEPS += \
./selex-fdk/libs/canopen-clib/CO.d \
./selex-fdk/libs/canopen-clib/CO_CAN_Msg.d \
./selex-fdk/libs/canopen-clib/CO_CRC.d \
./selex-fdk/libs/canopen-clib/CO_EMCY.d \
./selex-fdk/libs/canopen-clib/CO_FLASH.d \
./selex-fdk/libs/canopen-clib/CO_NMT.d \
./selex-fdk/libs/canopen-clib/CO_OD.d \
./selex-fdk/libs/canopen-clib/CO_OD_sign.d \
./selex-fdk/libs/canopen-clib/CO_OD_storage.d \
./selex-fdk/libs/canopen-clib/CO_Object.d \
./selex-fdk/libs/canopen-clib/CO_PDO.d \
./selex-fdk/libs/canopen-clib/CO_RPDO.d \
./selex-fdk/libs/canopen-clib/CO_SDO.d \
./selex-fdk/libs/canopen-clib/CO_SDOclient.d \
./selex-fdk/libs/canopen-clib/CO_SDOserver.d \
./selex-fdk/libs/canopen-clib/CO_SYNC.d \
./selex-fdk/libs/canopen-clib/CO_TPDO.d 

OBJS += \
./selex-fdk/libs/canopen-clib/CO.o \
./selex-fdk/libs/canopen-clib/CO_CAN_Msg.o \
./selex-fdk/libs/canopen-clib/CO_CRC.o \
./selex-fdk/libs/canopen-clib/CO_EMCY.o \
./selex-fdk/libs/canopen-clib/CO_FLASH.o \
./selex-fdk/libs/canopen-clib/CO_NMT.o \
./selex-fdk/libs/canopen-clib/CO_OD.o \
./selex-fdk/libs/canopen-clib/CO_OD_sign.o \
./selex-fdk/libs/canopen-clib/CO_OD_storage.o \
./selex-fdk/libs/canopen-clib/CO_Object.o \
./selex-fdk/libs/canopen-clib/CO_PDO.o \
./selex-fdk/libs/canopen-clib/CO_RPDO.o \
./selex-fdk/libs/canopen-clib/CO_SDO.o \
./selex-fdk/libs/canopen-clib/CO_SDOclient.o \
./selex-fdk/libs/canopen-clib/CO_SDOserver.o \
./selex-fdk/libs/canopen-clib/CO_SYNC.o \
./selex-fdk/libs/canopen-clib/CO_TPDO.o 


# Each subdirectory must supply rules for building sources it contributes
selex-fdk/libs/canopen-clib/CO.o: ../selex-fdk/libs/canopen-clib/CO.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_CAN_Msg.o: ../selex-fdk/libs/canopen-clib/CO_CAN_Msg.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_CAN_Msg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_CRC.o: ../selex-fdk/libs/canopen-clib/CO_CRC.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_CRC.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_EMCY.o: ../selex-fdk/libs/canopen-clib/CO_EMCY.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_EMCY.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_FLASH.o: ../selex-fdk/libs/canopen-clib/CO_FLASH.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_FLASH.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_NMT.o: ../selex-fdk/libs/canopen-clib/CO_NMT.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_NMT.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_OD.o: ../selex-fdk/libs/canopen-clib/CO_OD.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_OD.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_OD_sign.o: ../selex-fdk/libs/canopen-clib/CO_OD_sign.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_OD_sign.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_OD_storage.o: ../selex-fdk/libs/canopen-clib/CO_OD_storage.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_OD_storage.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_Object.o: ../selex-fdk/libs/canopen-clib/CO_Object.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_Object.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_PDO.o: ../selex-fdk/libs/canopen-clib/CO_PDO.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_PDO.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_RPDO.o: ../selex-fdk/libs/canopen-clib/CO_RPDO.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_RPDO.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_SDO.o: ../selex-fdk/libs/canopen-clib/CO_SDO.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_SDO.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_SDOclient.o: ../selex-fdk/libs/canopen-clib/CO_SDOclient.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_SDOclient.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_SDOserver.o: ../selex-fdk/libs/canopen-clib/CO_SDOserver.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_SDOserver.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_SYNC.o: ../selex-fdk/libs/canopen-clib/CO_SYNC.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_SYNC.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/libs/canopen-clib/CO_TPDO.o: ../selex-fdk/libs/canopen-clib/CO_TPDO.c selex-fdk/libs/canopen-clib/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/libs/canopen-clib/CO_TPDO.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

