################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../selex-fdk/common/src/sm_ble.c \
../selex-fdk/common/src/sm_button.c \
../selex-fdk/common/src/sm_cli.c \
../selex-fdk/common/src/sm_ec200s.c \
../selex-fdk/common/src/sm_http.c \
../selex-fdk/common/src/sm_http_header.c \
../selex-fdk/common/src/sm_led.c \
../selex-fdk/common/src/sm_modbus.c \
../selex-fdk/common/src/sm_modem.c \
../selex-fdk/common/src/sm_mqtt_client.c \
../selex-fdk/common/src/sm_security.c \
../selex-fdk/common/src/sm_spi_flash.c 

C_DEPS += \
./selex-fdk/common/src/sm_ble.d \
./selex-fdk/common/src/sm_button.d \
./selex-fdk/common/src/sm_cli.d \
./selex-fdk/common/src/sm_ec200s.d \
./selex-fdk/common/src/sm_http.d \
./selex-fdk/common/src/sm_http_header.d \
./selex-fdk/common/src/sm_led.d \
./selex-fdk/common/src/sm_modbus.d \
./selex-fdk/common/src/sm_modem.d \
./selex-fdk/common/src/sm_mqtt_client.d \
./selex-fdk/common/src/sm_security.d \
./selex-fdk/common/src/sm_spi_flash.d 

OBJS += \
./selex-fdk/common/src/sm_ble.o \
./selex-fdk/common/src/sm_button.o \
./selex-fdk/common/src/sm_cli.o \
./selex-fdk/common/src/sm_ec200s.o \
./selex-fdk/common/src/sm_http.o \
./selex-fdk/common/src/sm_http_header.o \
./selex-fdk/common/src/sm_led.o \
./selex-fdk/common/src/sm_modbus.o \
./selex-fdk/common/src/sm_modem.o \
./selex-fdk/common/src/sm_mqtt_client.o \
./selex-fdk/common/src/sm_security.o \
./selex-fdk/common/src/sm_spi_flash.o 


# Each subdirectory must supply rules for building sources it contributes
selex-fdk/common/src/sm_ble.o: ../selex-fdk/common/src/sm_ble.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_ble.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_button.o: ../selex-fdk/common/src/sm_button.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_button.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_cli.o: ../selex-fdk/common/src/sm_cli.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_cli.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_ec200s.o: ../selex-fdk/common/src/sm_ec200s.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_ec200s.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_http.o: ../selex-fdk/common/src/sm_http.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_http.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_http_header.o: ../selex-fdk/common/src/sm_http_header.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_http_header.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_led.o: ../selex-fdk/common/src/sm_led.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_led.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_modbus.o: ../selex-fdk/common/src/sm_modbus.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_modbus.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_modem.o: ../selex-fdk/common/src/sm_modem.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_modem.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_mqtt_client.o: ../selex-fdk/common/src/sm_mqtt_client.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_mqtt_client.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_security.o: ../selex-fdk/common/src/sm_security.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_security.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
selex-fdk/common/src/sm_spi_flash.o: ../selex-fdk/common/src/sm_spi_flash.c selex-fdk/common/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG '-DCMSIS_device_header=<stm32g0xx.h>' -DUSE_HAL_DRIVER -DSTM32G0B1xx -c -I../Core/Inc -I../USB_Device/App -I../USB_Device/Target -I../Drivers/STM32G0xx_HAL_Driver/Inc -I../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/bsp/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/common/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/cores/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/libs/canopen-clib" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/utils/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/cJSON" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/selex-fdk/thirdparties/littlefs" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/assign" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/config" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/service/sbp" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/board/porting/include" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/init" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/comm_od" -I"C:/Users/Admin/STM32CubeIDE/workspace_1.6.0/Selex_Battery_Module/SBM/app/co_app/od/manu_od" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"selex-fdk/common/src/sm_spi_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

